"""Canonical Ant-v5/PPO utilities for the ProxyGap project."""

from .ant_wrapper import (
    bounded_squared_signal_penalty,
    PitchBalanceEventTracker,
    ProxyGapAntWrapper,
    STEP_LOG_SCHEMA,
    forward_velocity_tracking_value,
    lateral_penalty_value,
    make_proxygap_ant_env,
    normalised_action_rate_penalty,
    orientation_penalty_value,
    project_action_l2_slew,
    quaternion_pitch_angle,
)
from .experiment import (
    CHECKPOINT_FRACTIONS,
    DEFAULT_PPO_CONFIG,
    checkpoint_targets,
    evaluate_model,
    resolve_ppo_config,
    select_representative_evaluation_seed,
)
from .divergence import (
    DEFAULT_EXTERNAL_HARM_METRICS,
    PairwiseProxyContrast,
    PairwiseWeightScreen,
    SeedDivergenceContrast,
    WeightDivergenceScreen,
    choose_minimal_departure_candidate,
    screen_pairwise_fixed_proxy,
    screen_divergence_candidates,
)
from .metrics import (
    CSV_SCHEMA,
    EpisodeMetrics,
    classify_termination,
    common_rescored_return,
    quaternion_tilt_angle,
)
from .protocol import protocol_freeze_status, validate_prospective_protocol
from .planar_transition import (
    PlanarCommandTransitionWrapper,
    QUARTER_TURN_ACTION_PERMUTATION,
    distill_quarter_turn_command_adapter,
    make_planar_transition_env,
    planar_velocity_tracking_value,
    quarter_turn_action,
    quaternion_yaw_angle,
    transfer_pretrained_policy,
    wrapped_angle_difference,
)
from .curved_gait import (
    CURVE_PROFILES,
    CurvedGaitCommandWrapper,
    make_curved_gait_env,
    pseudo_huber_penalty,
    transfer_curved_policy_with_contact_observation,
    transfer_planar_policy_to_curved_gait,
)
from .selection import (
    CandidateSummary,
    SelectionResult,
    project_selection_inputs,
    select_best_tested_coefficient,
)
from .two_experiment_protocol import validate_two_experiment_protocol

__all__ = [
    "CHECKPOINT_FRACTIONS",
    "CSV_SCHEMA",
    "bounded_squared_signal_penalty",
    "PitchBalanceEventTracker",
    "DEFAULT_PPO_CONFIG",
    "EpisodeMetrics",
    "ProxyGapAntWrapper",
    "STEP_LOG_SCHEMA",
    "checkpoint_targets",
    "evaluate_model",
    "classify_termination",
    "common_rescored_return",
    "make_proxygap_ant_env",
    "forward_velocity_tracking_value",
    "lateral_penalty_value",
    "normalised_action_rate_penalty",
    "orientation_penalty_value",
    "project_action_l2_slew",
    "quaternion_pitch_angle",
    "quaternion_tilt_angle",
    "resolve_ppo_config",
    "select_representative_evaluation_seed",
    "protocol_freeze_status",
    "validate_prospective_protocol",
    "DEFAULT_EXTERNAL_HARM_METRICS",
    "PairwiseProxyContrast",
    "PairwiseWeightScreen",
    "SeedDivergenceContrast",
    "WeightDivergenceScreen",
    "choose_minimal_departure_candidate",
    "screen_pairwise_fixed_proxy",
    "screen_divergence_candidates",
    "CandidateSummary",
    "SelectionResult",
    "project_selection_inputs",
    "select_best_tested_coefficient",
    "validate_two_experiment_protocol",
    "PlanarCommandTransitionWrapper",
    "QUARTER_TURN_ACTION_PERMUTATION",
    "distill_quarter_turn_command_adapter",
    "make_planar_transition_env",
    "planar_velocity_tracking_value",
    "quarter_turn_action",
    "quaternion_yaw_angle",
    "transfer_pretrained_policy",
    "wrapped_angle_difference",
    "CURVE_PROFILES",
    "CurvedGaitCommandWrapper",
    "make_curved_gait_env",
    "pseudo_huber_penalty",
    "transfer_curved_policy_with_contact_observation",
    "transfer_planar_policy_to_curved_gait",
]
